print("Welcome to the BMI Calculator")
weight = float(input("Enter your weight(in kg): "))
height = float(input("Enter your height(in meters): "))
bmi = weight/(height**2)
print(f"The BMI is: {round(bmi,2)}")