# x = len(12345)
y = len("hello")
print(y)
print(type("Hello"))
print(type(12345))
print(type(12.10))
print(type(True))
print(type(False))
print("Number of letters in your name: " + str(len(input("Enter your name: "))))